version: "3.8"

services:
  # express-app:
  #   build: .
  #   ports:
  #     - "${EXPRESS_PORT}:3000" # Replace ${EXPRESS_PORT} with your desired Express port from .env
  #   environment:
  #     - NODE_ENV=production # Set your Node environment variables here if needed
  #   depends_on:
  #     - postgres # Express depends on the PostgreSQL service

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: postgres # Replace dbname with your desired PostgreSQL database name from .env
      POSTGRES_USER: postgres # Replace dbuser with your desired PostgreSQL username from .env
      POSTGRES_PASSWORD: postgres # Replace dbpassword with your desired password from .env
    ports:
      - "5432:5432" # PostgreSQL port

  pgadmin:
    image: dpage/pgadmin4
    container_name: pg_admin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80" # UI for PostgreSQL port
    depends_on:
      - postgres # UI depends on the PostgreSQL service
